networks:
  dockernet:
    external:
      true

services:
  portainer.web:
    image: portainer/portainer-ce:sts
    container_name: portainer.web
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=http,https
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=development
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.homestack.me`)
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000

volumes:
  portainer_data: