version: "3.9"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

    environment:
      PUID: 1000 
      PGID: 1000 
    volumes:
      - ./config:/app/config # Make sure your local config directory exists