networks:
  dockernet:
    external: true
volumes:
  grafana_data:
    name: grafana_data

services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 3000:3000
    environment:
      - GF_LOG_LEVEL=debug
      # - GF_INSTALL_PLUGINS=plug01,plug02,plug03,...
      # - GF_INSTALL_PLUGINS=https://github.com/VolkovLabs/custom-plugin.zip
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
# grafana-cli plugins install
