networks:
  dockernet:
    external:
      true

volumes:
  pgsql_data:
    name: pgsql_data

services:
  database.pgsql:
    image: postgres:16-alpine
    container_name: database.pgsql
    restart: unless-stopped
    networks:
      - dockernet
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demodb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgsql_data:/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.pgsql-rtr.entrypoints=postgres
      - traefik.tcp.routers.pgsql-rtr.rule=HostSNI(`pgsql-db.homestack.me`)
      - traefik.tcp.routers.pgsql-rtr.tls=true
      - traefik.tcp.routers.pgsql-rtr.tls.passthrough=true
      - traefik.tcp.routers.pgsql-rtr.tls.certresolver=development
      - traefik.tcp.services.pgsql-svc.loadbalancer.server.port=5432