## traefik v3.yml

global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

log:
  level: INFO
  format: common # | json
  # filePath: /var/traefik/logs/traefik.log


entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
      # middlewares:
      #   # - https-mw@file
      #   - websocket-mw@file
  https:
    address: :443
    # http:
      # middlewares:
      #   - websocket-mw@file
  postgres:
    address: :5432

providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dyn
    watch: true



certificatesResolvers:
  development:
    acme:
      email: "kvruntime@proton.me"
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: http

