concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-local-container-personal-shell"
  url = "https://gitlab.com"
  id = 34362421
  token = "glrt-SabwyZi2xcJwNiVP4Ttd"
  token_obtained_at = 2024-04-02T19:00:02Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
