services:
  bind9_server:
    image: ubuntu/bind9:edge
    container_name: bind9_server
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - BIND9_USER=root
      - TZ=UTC
    volumes:
      - ./config:/etc/bind
      - ./zones:/etc/bind/zones
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind