services:
  traefik_proxy:
    image: traefik:v3.0
    container_name: traefik_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "8080:8080"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localdomain.com`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.middlewares=traefikauth
      - "traefik.http.middlewares.traefikauth.basicauth.users=ryuk:$$2y$$10$$4bRdNt3ZIurDiyBNpBMM8.X7yWGdQhToyHtSMX3jtCyLHyXwGN2A."