version: '3'

networks:
  app_network:
    external:
      true

# volumes:
#   odoo_volume:
#     external:
#       true


services:
  odoo_web:
    image: odoo:17
    container_name: odoo_web
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "8069:8069"
    environment:
    - HOST=postgres_db
    - USER=odoo_user
    - PASSWORD=odoo_password
    volumes:
      - ./config:/etc/odoo:ro
      - /mnt/d/Development/dockervolumes/odoo/data:/var/lib/odoo
      - /mnt/d/Development/dockervolumes/odoo/extra-addons:/mnt/extra-addons:rw




# user:admin
# password: in config file