networks:
  proxy_network:
    external:
      true

services:
  odoo_web:
    image: odoo:17
    container_name: odoo_web
    restart: unless-stopped
    depends_on:
      - odoo_db
    networks:
      - proxy_network
    # ports:
    #   - '8069:8069'
    environment:
      - HOST=odoo_db
      - USER=odoo_user
      - PASSWORD=odoo_password
    volumes:
      - ./config:/etc/odoo:ro
      - /mnt/d/Development/dockervolumes/odoo/odoo_web/data:/var/lib/odoo
      - /mnt/d/Development/dockervolumes/odoo/odoo_web/extra-addons:/mnt/extra-addons:rw
    labels:
      - traefik.http.routers.odoo_web.rule=Host(`odoo.wslubuntu.com`)

  odoo_db:
    image: postgres:16-alpine
    container_name: odoo_db
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 20M
        limits:
          cpus: '0.50'
          memory: 150M
    networks:
      - proxy_network
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/d/Development/dockervolumes/odoo/odoo_db/pgdata:/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.odoo_db.entryPoints=postgres
      - traefik.tcp.routers.odoo_db.rule=HostSNI(`*`)
      - traefik.tcp.routers.odoo_db.service=odoo_db
      - traefik.tcp.services.odoo_db.loadbalancer.server.port=5432