networks:
  back_net:
    external:
      true
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.homestack.me
    # ports:
    #   - "25:25"
    #   - "465:465"
    #   - "587:587"
    #   - "993:993"
    networks:
      - back_net
    volumes:
      - /appdata/volumes/mailserver/_data:/var/mail/
      - /appdata/volumes/mailserver/_data:/var/mail-state/
      - /appdata/volumes/mailserver/_data:/var/log/mail/
      - /appdata/volumes/mailserver/_data:/tmp/docker-mailserver/
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - MAIL_USER=user
      - MAIL_PASS=password
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
    labels:
     - traefik.enable=true
     - traefik.http.routers.mailserver-rtr.entrypoints=http
     - traefik.http.routers.mailserver-rtr.rule=Host(`mail.homestack.me`)
     - traefik.http.routers.mailserver-rtr.tls=true
     - traefik.http.routers.mailserver-rtr.tls.certresolver=development
     - traefik.http.services.mailserver-svc.loadbalancer.server.port=25