networks:
  dockernet:
    external:
      true

services:
  portainer_web:
    image: portainer/portainer-ce:sts
    container_name: portainer_web
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /appdata/volumes/portainer/_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=http,https
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=development
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.homestack.me`)
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000