
networks:
  proxy_network:
    external:
      true
services:
  wordpress_web:
    image: wordpress:php8.1-fpm-alpine
    restart: always
    container_name: wordpress_web
    # ports:
    #   - 127.0.0.1:9080:80
    # networks:
    #   - proxy_network
    environment:
      - WORDPRESS_DB_HOST=wordpress_mariadb
      - WORDPRESS_DB_USER=wordpress_01
      - WORDPRESS_DB_PASSWORD=wordpress_01
      - WORDPRESS_DB_NAME=wordpress_01
      - WORDPRESS_TABLE_PREFIX=wordpress_
    volumes:
      - /mnt/d/Development/dockervolumes/wordpress_01:/var/www/html
    labels:
      - traefik.enable=true
    #   - traefik.http.routers.wordpress_web.endpoints=http
    #   - treafik.http.routers.wordpress_web.rule=Host(`wordpress.wslubuntu.com`)
    #   - traefik.http.services.wordpress_web.loadbalancer.server.port=80

  wordpress_mariadb:
    image: mariadb:lts
    restart: always
    container_name: wordpress_mariadb
    # networks:
    #   - proxy_network
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
    volumes:
      - /mnt/d/Development/dockervolumes/mysql_db:/var/lib/mysql
