## traefik v3.yml

global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

log:
  level: INFO
  format: common # | json


entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  postgres:
    address: :5432

providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true



certificatesResolvers:
  development:
    acme:
      email: "kvruntime@proton.me"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: /var/lib/traefik/certs/acme.json
      keyType: RSA4096
      httpChallenge:
        entryPoint: http

