networks:
  dockernet:
    external:
      true

volumes:
  traefikproxy_data:
    name: traefikproxy_data
      
services:
  traefikproxy:
    image: traefik:v3.1
    restart: unless-stopped
    privileged: true
    networks:
      - dockernet
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configs.yml:/etc/traefik/configs.yml:ro
      - traefikproxy_data:/var/lib/traefik/certs:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=http,https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.local.kvruntime.com`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=local.kvruntime.com
      - traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.local.kvruntime.com
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080


