version: "3"
networks:
  app_network:
    external:
      true
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - 127.0.0.1:9443:9443
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8000:8000
    volumes:
      - /d/Development/dockervolumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock