version: "3"

networks:
  app_network:
    external:
      true


services:
  mysql_db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      # - MYSQL_USER=mysql
      # - MYSQL_PASSWORD=mysql
      # - MYSQL_DATABASE=mysql
    networks:
      - app_network
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - /d/Development/dockervolumes/mysql_db:/var/lib/mysql