networks:
  dockernet:
    external: true
volumes:
  ollama_data:
    name: ollama_data
services:
  ollama:
    image: ollama/ollama:rocm
    restart: unless-stopped
    networks:
      - dockernet
    # ports:
    #   - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
