# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

networks:
  dockernet:
    external: true

secrets:
  webpassword:
    file: ./webpassword.txt

services:
  pihole:
    image: pihole/pihole:nightly
    restart: unless-stopped
    # network_mode: host
    networks:
      - dockernet
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp
      - 22222:80/tcp
    secrets:
      - webpassword
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD_FILE=/run/secrets/webpassword
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole-rtr.entrypoints=http,https
      - traefik.http.routers.pihole-rtr.rule=Host(`phihole.local.kvruntime.com`)
      - traefik.http.routers.pihole-rtr.tls=true
      - traefik.http.routers.pihole-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.pihole-svc.loadbalancer.server.port=80
