version: '3'

networks:
  app_network:
    external: true

# volumes:
#   postgres_volume:
#     external: true

services:
  postgres_db:
    image: postgres:16-bullseye
    container_name: postgres_db
    restart: unless-stopped
    networks:
      - app_network
    ports:
       - '5432:5432'
    volumes:
       - /mnt/d/Development/dockervolumes/postgres/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
